### ISSUE TITLE
Minor Input component styling error on IE11

### ISSUE THREAD

**Issue by akoushke** [collab-ui/collab-ui#85]
The input's placeholder is not aligned properly on IE11

![collab_bug](https://user-images.githubusercontent.com/14226615/53361301-4f934680-38ec-11e9-9e9c-f880075720c9.png)

**Comment by pauljeter** [comment]
Collab-ui provides support down to IE11, however we have chosen to provide graceful degradation rather than pixel perfect support. This means that we ensure that all components are functional in ie11 however they may not look exactly as they do in the evergreen browsers. One of the issues with the spacing/padding/margin in IE11 is that there is variation between ie11 in Windows 10 vs  ie 11 Windows 7. Microsoft is only supporting bug fixes in IE11 and thus we are only supporting it with fallbacks on features that are not fully supported (i.e. font spacing, flex box, etc.)
